### ISSUE TITLE
CSS Custom Properties

### ISSUE THREAD

**Issue by kevinSuttle** [textmate/css.tmbundle#27]
Live example: 

```css
:root {
	--ThemeColor: "#3c790a"
}

ui-widget {
	background-color: var(--ThemeColor);
}
```

Screenshot in case it changes. 
<img width="339" alt="screen shot 2016-09-22 at 2 31 15 pm" src="https://cloud.githubusercontent.com/assets/95672/18761011/4b500e9e-80d1-11e6-92fa-2b915e5a9f4d.png">
